'use client';

import { ApiError } from '@neon-adda/shared/web/client';
import { ShieldCheck } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { CodeInput, FormError, SubmitButton } from '@/components/ui/form';
import { api } from '@/lib/browser-api';

interface Setup {
  secret: string;
  qrCodeDataUrl: string;
  setupToken: string;
}

export function TwoFactorSetup({ required }: { required: boolean }) {
  const [setup, setSetup] = useState<Setup | null>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    api
      .request<Setup>('/auth/admin/2fa/setup', { method: 'POST' })
      .then((result) => !cancelled && setSetup(result))
      .catch(
        (err) => !cancelled && setError(err instanceof ApiError ? err.title : 'Could not start the setup.'),
      );
    return () => {
      cancelled = true;
    };
  }, []);

  async function enable(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!setup) return;
    setPending(true);
    setError(null);
    try {
      await api.request('/auth/admin/2fa/enable', {
        method: 'POST',
        body: JSON.stringify({
          setupToken: setup.setupToken,
          code: new FormData(event.currentTarget).get('code'),
        }),
      });
      // A full load, so nothing rendered for the previous session survives in the router cache.
      window.location.replace('/');
    } catch (err) {
      setError(err instanceof ApiError ? err.title : 'Could not verify the code.');
    } finally {
      setPending(false);
    }
  }

  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
      <div className="flex items-center gap-2">
        <ShieldCheck className="size-5 text-brand" />
        <h1 className="font-display text-xl font-bold text-gray-900">Two-factor authentication</h1>
      </div>
      <p className="mt-2 text-sm text-gray-500">
        {required ? 'Admin accounts need a second step at sign-in. ' : ''}
        Scan this code with Google Authenticator, Microsoft Authenticator or 1Password, then enter the 6-digit
        code it shows.
      </p>

      {setup ? (
        <form onSubmit={enable} className="mt-5 space-y-4">
          {/* A data URL generated by the API, so next/image has nothing to optimise. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={setup.qrCodeDataUrl}
            alt="QR code for your authenticator app"
            className="mx-auto size-44"
          />
          <details className="text-center text-xs text-gray-500">
            <summary className="cursor-pointer">Can’t scan it?</summary>
            <p className="mt-2 font-mono break-all text-gray-700 select-all">{setup.secret}</p>
          </details>
          <CodeInput name="code" required autoFocus />
          <FormError message={error} />
          <SubmitButton pending={pending}>Turn on</SubmitButton>
        </form>
      ) : (
        <div className="mt-5 space-y-4">
          {!error && <div className="mx-auto size-44 animate-pulse rounded-lg bg-gray-100" />}
          <FormError message={error} />
        </div>
      )}
    </div>
  );
}
